# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christopher Velez
title: Cybersecurity Student
email: cvelez159@gmail.com
website: c-velez.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  c-velez
linkedin_username: cvelez159

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Add content here

  I am most skilled in: <mark>Network analysis</mark> and <mark>log analysis</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: To Do List
        link: github.com/c-velez
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/c-velez/ToDoList
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This project was written for a class.
        description: | # this will include new lines to allow paragraphs
          Describe the project

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: P3F
        link: p3f.llc
        # link_text: boringcompany.com
        sub_title: Threat Hunter
        caption: June 2020 - April 2021
        #        quote: >
        description: | # this will include new lines to allow paragraphs
            - Security operations and threat hunting subject matter expert; developed ground up processes and procedures for client security operations center
            - Lef client through monitoring and alerting strategy via Mitre ATT&CK matrix; verified data sources and updated/created queries
            - Tailored 150 out-of-box Elastic Alerts for client environment; worked with SIEM on-boarding team to create custom parsers for 5 log sources
            - Worked with Information System Security Engineer to validate 10 Red Team findings; tested fixes implemented by development team

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Central Florida
        caption: January 2020 - December 2023 (Expected)
        sub_title: BSc Information Security
      - layout: left
        title: United States Air Force: Undergraduate Cyber Training
        caption: May 2016 - November 2016
        sub_title: CompTIA Security+ (Oct 2022)
      - layout: left
        title: University of Central Florida
        caption: August 2008 - December 2012
        sub_title: BSc Aerospace Engineering

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
