# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christopher Velez
title: Cyber Security Student | Air Force Veteran
email: cvelez159@gmail.com
website: c-velez.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  c-velez
linkedin_username: cvelez159

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Current Course Work (Spring 2022)
about_content: |
    - **Foundations of Human Computer Interaction**

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: To Do List
        link: github.com/c-velez/ToDoList
        # link_text: Project Website
        additional_links:
          - title:  To Do List
            icon: fab fa-github
            url: github.com/c-velez/ToDoList
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
          #        quote: >
          #          This project was written for a class.
        description: | # this will include new lines to allow paragraphs
          A Java GUI application that allows users to create a To Do List. Users are able to add items to a list, mark items as complete or incomplete, sort items by date, and view items by completionstatus

      - layout: top-middle
        title: Inventory Manager
        link: github.com/c-velez/InventoryManager
        additional_links:
          - title: Inventory Manager
            icon: fab fa-github
            url: github.com/c-velez/InventoryManager
        description: |
          A Java GUI application that allows a user to manage an inventory of items. Users are able to add and delete items, apply prices to items, and attach a unique serial number to each item.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: P3F
        link: p3f.llc
        sub_title: Threat Hunter
        caption: June 2020 - April 2021
        description: | # this will include new lines to allow paragraphs
            - Security operations and threat hunting subject matter expert; developed ground up processes and procedures for client security operations center
            - Led client through monitoring and alerting strategy via Mitre ATT&CK matrix; verified data sources and updated/created queries
            - Tailored 150 out-of-box Elastic Alerts for client environment; worked with SIEM on-boarding team to create custom parsers for 5 log sources
            - Worked with Information System Security Engineer to validate 10 Red Team findings; tested fixes implemented by development team

      - layout: left
        title: United States Air Force
        sub_title: Deputy Chief, Mission Management
        caption: June 2018 - December 2019
        description: |
            - Directed more than 60-member cross-functional team to enable access for national security operations
            - Managed 24/7 watch office; required specialized training and access to conduct operations against high value targets
            - Used networking knowledge, risk management, and exploitation methodology to advice high level network operators

      - layout: left
        title: United States Air Force
        sub_title: Commander, Cyberspace Threat Intelligence Center
        caption: November 2016 - June 2018
        description: |
            - Built and codified new Air Force mission, leading more than 60-member multi-disciplined team in cyberspace threat intelligence
            - Demonstrated effective collaboration with customers; technical intelligence reporting resulted in over 400 defensive network actions
            - Devloped actionable intelligence reporting team; integrated intelligence with technical data tailored for responders and executives
            - Integrated multiple agencies to centralize disrtribution of intelligence analysis - expedited information sharing, boosted technical and intelligence reporting 300%
            - Crafted indications and warning tipping process for enterprise level security operations center; reduced notification time by 66% - days to hours

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of Central Florida
        caption: January 2020 - December 2023 (Expected)
        sub_title: BSc Information Security

      - layout: top-middle
        title: United States Air Force 
        sub_title: Cyber Warfare Operations
        caption: October 2019 - December 2019

      - layout: top-middle
        title: United States Air Force
        caption: May 2016 - November 2016 
        sub_title: Undergraduate Cyber Training

      - layout: top-middle
        title: University of Central Florida
        caption: August 2008 - December 2012
        sub_title: BSc Aerospace Engineering

  - title: Skills
    layout: list
    content:
      - layout: left
        title: Languages
        description: | 
            - Bash
            - Python
            - Java/JUnit 5
            - UML

      - layout: left
        title : Tools
        description: |
            - IntelliJ
            - Git
            - Wireshark
            - nmap
            - VMware
            - Nessus
            - \*nix
      - layout: left
        title: Other
        description: |
            - Mitre ATT&CK
            - Basic Static and Dynamic Malware Analysis
            - Cryptography
            - Network Security Monitoring
                - Zeek
                - Snort
            - Log Analysis
            - NetCat
            - Virtual Lab Creation - VMware
            - Agile/SCRUM

      - layout: left
        title: Extra Curriculars
        description: |
            - Hack@UCF
            - National Cyber League (96th Percentile - Individual)
            - Hive Storm
            - NSA CodeBreakers Challenge
            - SANS Holiday Hack Challenge

  - title: Other
    layout: list
    content:
        - layout: left
          description: |
              - <a href="/write_ups/">Write Ups</a>
              - <a href="/reading_list.md">Reading List</a>
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
